import { addDays, endOfMonth, format, getDay, startOfMonth, subDays } from 'date-fns';
import { redirect } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { getAppData } from '@/lib/data';
import { currency } from '@/lib/format';

export default async function CalendarPage() {
  const { user, subscriptions }=await getAppData();if(!user)redirect('/login'); const now=new Date(); const start=startOfMonth(now); const first=subDays(start,getDay(start)); const last=endOfMonth(now); const days=Array.from({length:42},(_,i)=>addDays(first,i));
  return <AppShell email={user.email ?? null}><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 lg:px-10"><header><p className="text-sm text-stone-500">Plan before payments hit</p><h1 className="mt-1 font-serif text-3xl tracking-tight sm:text-4xl">Renewal calendar</h1></header><section className="card mt-7 overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="panel-title">{format(now,'MMMM yyyy')}</h2><span className="text-xs font-semibold text-stone-500">{subscriptions.filter(s=>s.status==='active').length} active subscriptions</span></div><div className="grid grid-cols-7 border-b bg-stone-50">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div className="px-2 py-3 text-center text-[10px] font-bold uppercase tracking-wide text-stone-400" key={d}>{d}</div>)}</div><div className="grid grid-cols-7">{days.map(day=>{const inMonth=day.getMonth()===now.getMonth();const key=format(day,'yyyy-MM-dd');const events=subscriptions.filter(s=>s.status==='active'&&s.next_renewal_date===key);return <div key={key} className={`min-h-[85px] border-b border-r p-1.5 sm:min-h-[115px] sm:p-2.5 ${!inMonth?'bg-stone-50/70 text-stone-300':''}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-xs font-semibold ${key===format(now,'yyyy-MM-dd')?'bg-ink text-white':''}`}>{format(day,'d')}</span>{events.map(s=><a href={`/subscriptions/${s.id}`} key={s.id} className="mt-1 block truncate rounded-md bg-violet-100 px-1.5 py-1 text-[9px] font-bold text-violet-800 sm:text-[10px]">{s.service_name}<span className="hidden sm:inline"> · {currency(Number(s.cost),s.currency)}</span></a>)}</div>})}</div></section><p className="mt-4 text-xs leading-5 text-stone-500">Calendar dates reflect the renewal dates you entered. You can change a renewal date from the subscription detail page.</p></div></AppShell>;
}
