'use client';

import Link from 'next/link';
import { ExternalLink, MoreHorizontal, Trash2 } from 'lucide-react';
import { useState, useTransition } from 'react';
import { deleteSubscription, logUsage, setSubscriptionStatus } from '@/app/actions';
import { categoryLabel, currency, dateLabel, dueLabel } from '@/lib/format';
import type { Subscription } from '@/lib/types';

const color: Record<string,string> = { streaming: 'bg-red-100 text-red-700', software:'bg-violet-100 text-violet-700', gym:'bg-orange-100 text-orange-700', cloud:'bg-sky-100 text-sky-700', news:'bg-amber-100 text-amber-700', other:'bg-stone-100 text-stone-700' };
export function SubscriptionRow({ subscription, usedToday }: { subscription: Subscription; usedToday: boolean }) {
  const [menu, setMenu] = useState(false); const [pending, startTransition] = useTransition(); const inactive = subscription.status !== 'active';
  const run=(fn:()=>Promise<void>)=>startTransition(async()=>{try{await fn()}catch{alert('Something went wrong. Please try again.')}});
  return <article className={`grid grid-cols-[auto_1fr_auto] items-center gap-3 border-b py-4 last:border-0 md:grid-cols-[auto_1fr_auto_auto] ${inactive?'opacity-60':''}`}><div className={`grid h-10 w-10 place-items-center rounded-xl text-sm font-bold ${color[subscription.category]}`}>{subscription.service_name.slice(0,1).toUpperCase()}</div><Link href={`/subscriptions/${subscription.id}`} className="min-w-0"><div className="truncate font-bold">{subscription.service_name}</div><div className="mt-0.5 text-xs text-stone-500">{categoryLabel(subscription.category)} · {currency(subscription.cost, subscription.currency)} / {subscription.billing_cycle === 'monthly' ? 'mo' : 'yr'}</div></Link><div className="hidden text-right md:block"><div className={`text-xs font-bold ${subscription.status==='active'&&dueLabel(subscription.next_renewal_date).includes('2')?'text-red-600':''}`}>{inactive ? categoryLabel(subscription.status) : dueLabel(subscription.next_renewal_date)}</div><div className="mt-0.5 text-[11px] text-stone-500">{dateLabel(subscription.next_renewal_date)}</div></div><div className="relative flex items-center gap-1"><button disabled={pending||inactive||usedToday} onClick={()=>run(()=>logUsage(subscription.id))} className={`hidden rounded-lg px-2.5 py-2 text-xs font-bold sm:block ${usedToday?'bg-lime text-ink': 'bg-stone-100 text-stone-700 hover:bg-stone-200'} disabled:cursor-default`}>{usedToday ? 'Logged today' : 'Used today'}</button><button onClick={()=>setMenu(!menu)} className="rounded-lg p-2 text-stone-500 hover:bg-stone-100"><MoreHorizontal size={18}/></button>{menu&&<div className="absolute right-0 top-10 z-10 w-44 rounded-xl border bg-white p-1.5 shadow-lg"><Link onClick={()=>setMenu(false)} href={`/subscriptions/${subscription.id}`} className="block rounded-lg px-3 py-2 text-xs font-semibold hover:bg-stone-50">View details</Link>{subscription.renewal_url&&<a href={subscription.renewal_url} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-semibold hover:bg-stone-50">Renew on site <ExternalLink size={12}/></a>}<button onClick={()=>run(()=>setSubscriptionStatus(subscription.id,subscription.status==='paused'?'active':'paused'))} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold hover:bg-stone-50">{subscription.status==='paused'?'Resume':'Pause'}</button><button onClick={()=>{if(confirm(`Remove ${subscription.service_name}? This cannot be undone.`))run(()=>deleteSubscription(subscription.id))}} className="flex w-full items-center gap-1 rounded-lg px-3 py-2 text-left text-xs font-semibold text-red-600 hover:bg-red-50"><Trash2 size={12}/>Delete</button></div>}</div></article>;
}
