'use client';

import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { ArrowRight, Check, LockKeyhole } from 'lucide-react';

export default function LoginPage() {
  const [mode, setMode] = useState<'login' | 'signup'>('login');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setMessage(''); const supabase = createClient();
    const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${location.origin}/auth/callback` } });
    setBusy(false);
    if (result.error) return setMessage(result.error.message);
    if (mode === 'signup' && !result.data.session) return setMessage('Check your inbox to confirm your account.');
    location.assign('/dashboard');
  }
  async function magicLink() { setBusy(true); const { error } = await createClient().auth.signInWithOtp({ email, options: { emailRedirectTo: `${location.origin}/auth/callback` } }); setBusy(false); setMessage(error ? error.message : 'Magic link sent — check your inbox.'); }
  return <main className="min-h-screen bg-[#f7f7f3] p-5 text-ink md:grid md:grid-cols-2 md:p-8">
    <section className="relative hidden overflow-hidden rounded-[28px] bg-[#282a25] p-11 text-white md:block"><div className="absolute right-[-80px] top-[-70px] h-64 w-64 rounded-full bg-lime opacity-20" /><div className="relative"><div className="mb-20 flex items-center gap-2 text-2xl font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-lime text-lg text-ink">s</span>SubTrack</div><h1 className="max-w-md font-serif text-5xl leading-[1.1]">Make every subscription earn its place.</h1><p className="mt-6 max-w-md text-base leading-7 text-stone-300">See every renewal in one calm place, catch waste early, and decide what stays.</p><div className="mt-12 grid gap-4">{['Never miss a trial ending', 'Log real usage in one tap', 'Renew safely on the service site'].map(x => <div className="flex items-center gap-3 text-sm" key={x}><span className="grid h-6 w-6 place-items-center rounded-full bg-lime text-ink"><Check size={14}/></span>{x}</div>)}</div></div></section>
    <section className="mx-auto flex w-full max-w-md flex-col justify-center py-12 md:py-0"><div className="mb-9 md:hidden"><div className="flex items-center gap-2 text-2xl font-bold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-lime">s</span>SubTrack</div></div><p className="mb-2 text-sm text-stone-500">Welcome to SubTrack</p><h2 className="font-serif text-4xl tracking-tight">{mode === 'login' ? 'Welcome back' : 'Start tracking smarter'}</h2><p className="mt-3 text-sm leading-6 text-stone-500">{mode === 'login' ? 'Log in to see what is renewing next.' : 'Set up your private subscription home in a minute.'}</p><form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-semibold">Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@example.com" className="mt-2 w-full rounded-xl border border-stone-200 bg-white px-4 py-3 outline-none transition focus:border-violet focus:ring-4 focus:ring-violet/10" /></label><label className="block text-sm font-semibold">Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} required placeholder="At least 6 characters" className="mt-2 w-full rounded-xl border border-stone-200 bg-white px-4 py-3 outline-none transition focus:border-violet focus:ring-4 focus:ring-violet/10" /></label>{message && <p className="rounded-lg bg-stone-100 p-3 text-sm text-stone-700">{message}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3.5 text-sm font-bold text-white transition hover:bg-black disabled:opacity-60">{busy ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Create account'} <ArrowRight size={16}/></button></form><button disabled={!email || busy} onClick={magicLink} className="mt-3 w-full rounded-xl border border-stone-200 bg-white px-4 py-3 text-sm font-semibold text-stone-700 disabled:opacity-50">Email me a magic link</button><p className="mt-7 text-center text-sm text-stone-500">{mode === 'login' ? 'New here?' : 'Already have an account?'} <button onClick={()=>{setMode(mode === 'login' ? 'signup' : 'login');setMessage('')}} className="font-bold text-violet">{mode === 'login' ? 'Create an account' : 'Log in'}</button></p><p className="mt-10 flex items-center justify-center gap-2 text-center text-xs text-stone-400"><LockKeyhole size={12}/> Your subscription data stays private to your account.</p></section>
  </main>;
}
