import { redirect } from 'next/navigation';
import { BellRing, CalendarClock, CircleDollarSign, Lightbulb, Sparkles } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { SubscriptionForm } from '@/components/subscription-form';
import { SubscriptionRow } from '@/components/subscription-row';
import { ReminderAlert } from '@/components/reminder-alert';
import { getAppData } from '@/lib/data';
import { currency, daysUntil, monthlyCost } from '@/lib/format';

export default async function Dashboard() {
  const { user, settings, subscriptions, usage, notifications } = await getAppData(); if (!user || !settings) redirect('/login');
  const active = subscriptions.filter(s=>s.status==='active'); const total = active.reduce((sum,s)=>sum+monthlyCost(Number(s.cost),s.billing_cycle),0); const due = active.filter(s=>daysUntil(s.next_renewal_date)>=0&&daysUntil(s.next_renewal_date)<=7); const today = new Date().toISOString().slice(0,10); const usedToday = new Set(usage.filter(l=>l.logged_date===today).map(l=>l.subscription_id));
  const usageBySub = new Map<string,Set<string>>(); usage.forEach(l=>{const set=usageBySub.get(l.subscription_id)||new Set<string>();set.add(l.logged_date);usageBySub.set(l.subscription_id,set)});
  const valuable = active.find(s=>(usageBySub.get(s.id)?.size??0)>=4); const next = active[0]; const reminder = notifications.find(n => { if (n.type !== 'renewal_reminder') return false; const sub = subscriptions.find(s => s.id === n.subscription_id); return sub && sub.status === 'active'; }); const reminderSub = reminder ? subscriptions.find(s => s.id === reminder.subscription_id) : undefined;
  return <AppShell email={user.email ?? null}><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 lg:px-10"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm text-stone-500">Your subscription home</p><h1 className="font-serif text-3xl tracking-tight sm:text-4xl">Good morning{user.user_metadata.full_name ? `, ${user.user_metadata.full_name}` : ''}</h1></div><SubscriptionForm /></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Monthly spend" value={currency(total)} note="Active subscriptions only" color="bg-lime" icon={<CircleDollarSign size={18}/>}/><Stat title="Active subscriptions" value={String(active.length)} note={`${new Set(active.map(s=>s.category)).size} categories tracked`} color="bg-violet-100 text-violet-700" icon={<Sparkles size={18}/>}/><Stat title="Due this week" value={currency(due.reduce((sum,s)=>sum+Number(s.cost),0))} note={`${due.length} renewal${due.length===1?'':'s'} coming up`} color="bg-orange-100 text-orange-700" icon={<CalendarClock size={18}/>}/><Stat title="Open reminders" value={String(notifications.filter(n=>{const sub=subscriptions.find(s=>s.id===n.subscription_id);return !sub||sub.status==='active'}).length)} note="We resend until acknowledged" color="bg-rose-100 text-rose-700" icon={<BellRing size={18}/>}/></section>
    <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(310px,.75fr)]"><section><div className="mb-3 flex items-center justify-between"><h2 className="panel-title">Your subscriptions</h2><span className="text-xs font-semibold text-stone-500">Sorted by renewal date</span></div><div className="card px-5">{subscriptions.length ? subscriptions.map(s=><SubscriptionRow key={s.id} subscription={s} usedToday={usedToday.has(s.id)}/>) : <div className="py-16 text-center"><h3 className="font-serif text-xl">Nothing here yet</h3><p className="mt-2 text-sm text-stone-500">Add your first subscription to make renewals feel manageable.</p><div className="mt-4"><SubscriptionForm /></div></div>}</div></section>
      <aside className="space-y-6"><section className="card p-5"><div className="mb-4 flex items-center justify-between"><h2 className="panel-title">Next reminder</h2><BellRing size={17} className="text-violet"/></div>{reminder&&reminderSub?<><ReminderAlert id={reminder.id} title={`${reminderSub.service_name} needs your attention`} body={String(reminder.metadata?.message ?? `Your renewal is coming up. You can renew on the official service site when ready.`)}/><div className="mt-3 flex gap-2">{reminderSub.renewal_url&&<a href={reminderSub.renewal_url} target="_blank" rel="noreferrer" className="action bg-ink text-white">Renew on site ↗</a>}<a href={`/subscriptions/${reminderSub.id}`} className="action bg-stone-100 text-stone-700">View details</a></div></>:next?<><div className="rounded-xl bg-orange-50 p-4"><p className="text-sm font-bold">{next.service_name} renews in {Math.max(0,daysUntil(next.next_renewal_date))} days</p><p className="mt-1 text-xs leading-5 text-stone-600">Your {currency(Number(next.cost),next.currency)} {next.billing_cycle} plan is coming up. We’ll use your {settings.reminder_days_before}-day preference.</p></div><div className="mt-3 flex gap-2">{next.renewal_url&&<a href={next.renewal_url} target="_blank" rel="noreferrer" className="action bg-ink text-white">Renew on site ↗</a>}<a href={`/subscriptions/${next.id}`} className="action bg-stone-100 text-stone-700">View details</a></div></>:<p className="subtle">Add a subscription to start tracking reminders.</p>}</section>
        <section className="card p-5"><div className="mb-4 flex items-center justify-between"><h2 className="panel-title">Usage this week</h2><span className="pill bg-violet-50 text-violet">Self-reported</span></div><div className="grid grid-cols-7 gap-1.5">{['M','T','W','T','F','S','S'].map((day,i)=><div key={`${day}${i}`} className="text-center"><div className="mx-auto w-5 rounded-t bg-violet" style={{height:`${[31,45,25,56,40,19,49][i]}px`,opacity:i===5?.25:1}} /><span className="mt-2 block text-[10px] font-bold text-stone-400">{day}</span></div>)}</div><p className="mt-4 border-t pt-3 text-xs text-stone-500">Tap <b className="text-ink">Used today</b> whenever you use a service. It informs keep-or-cancel nudges.</p></section></aside></div>
    {(valuable || (reminderSub && reminderSub.status === 'active')) && <section className="mt-7 flex items-start gap-4 rounded-2xl bg-ink p-5 text-white sm:items-center"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/15 text-lime"><Lightbulb size={20}/></span><div><h2 className="text-sm font-bold">{valuable ? `${valuable.service_name} looks worth keeping` : 'A renewal needs your attention'}</h2><p className="mt-1 text-xs leading-5 text-stone-300">{valuable ? `You’ve logged activity on ${usageBySub.get(valuable.id)?.size} of the last 7 days. Set it to renewal-ready so you don’t lose access.` : `${reminderSub?.service_name} has an open renewal reminder. Review it before the billing date.`}</p></div>{valuable&&<a href={`/subscriptions/${valuable.id}`} className="ml-auto hidden shrink-0 rounded-lg bg-lime px-3 py-2 text-xs font-bold text-ink sm:block">Review it</a>}</section>}
  </div></AppShell>;
}
function Stat({title,value,note,color,icon}:{title:string;value:string;note:string;color:string;icon:React.ReactNode}){return <article className="card p-5"><span className={`grid h-9 w-9 place-items-center rounded-xl ${color}`}>{icon}</span><p className="mt-4 text-xs font-bold text-stone-500">{title}</p><p className="mt-1 text-2xl font-bold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-stone-500">{note}</p></article>}
